# Generated by Django 5.0.2 on 2024-02-21 09:35

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('found_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='posts.foundpost')),
            ],
        ),
        migrations.CreateModel(
            name='LostPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('lost_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='posts.lostpost')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
