# Generated by Django 5.0.2 on 2024-02-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_foundphoto_lostphoto_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundpost',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=44, max_digits=64, null=True),
        ),
        migrations.AlterField(
            model_name='foundpost',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=44, max_digits=64, null=True),
        ),
        migrations.AlterField(
            model_name='lostpost',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=44, max_digits=64, null=True),
        ),
        migrations.AlterField(
            model_name='lostpost',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=44, max_digits=64, null=True),
        ),
    ]
