# Generated by Django 5.0.2 on 2024-04-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
